name: Schedule Smoke Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "Triggered at: $(date -u) (UTC)"
          echo "Triggered at: $(date)"
